- name: Install dependencies
  apt:
    name: npm
    update_cache: yes
    state: present


- name: Create Frontend Directory
  file:
    path: /var/www/html/frontend
    state: directory

- name: Clone GIT Repo from hub
  git:
    repo: https://github.com/sreenathzs1/frontend.git
    dest: /var/www/html/frontend

- name: NPM INSTALL latest version
  npm:
    path: /var/www/html/frontend
    state: latest

- name: npm build
  command: npm run build
  args:
    chdir: "/var/www/html/frontend"  

- name: Replace content
  replace:
    path: /etc/nginx/sites-enabled/default
    regexp: root /var/www/html;
    replace: root /var/www/html/frontend/dist;


- name: Start Nginx
  systemd:
    state: restarted
    name: nginx
    enabled: yes


- name: Copy systemd frontend npm start Service file
  template:
    src: npmstart.service
    dest: /etc/systemd/system/npmstart.service
    mode: 0644
    owner: root
    group: root

- name: Start npm  Service
  systemd:
    name: npmstart.service
    daemon_reload: yes
    state: restarted
    enabled: yes