- name: Install dependencies
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: present

- name: Clone GIT Repo
  git:
    repo: https://github.com/sreenathzs1/frontend.git
    dest: /var/www/html/




- name: Start Nginx
  systemd:
    state: restarted
    name: nginx
    enabled: yes